version: '3.4'

x-nodejs: &nodejs
  build:
    context: ../
    dockerfile: .dockerdev/Dockerfile
  image: frontend-dev:0.1.0
  tmpfs:
    - /tmp
  stdin_open: true
  tty: true

services:
  nextjs:
    <<: *nodejs
    command: yarn dev
    volumes:
      - ../:/home/www/frontend:cached
      - node_modules:/home/www/frontend/node_modules
    ports:
      - '4000:4000'

volumes:
  node_modules:
